<!-- progres-->
<div class="col-md-4">
    <div class="table-responsive table-sm ">
        <table class="table table-striped table-earning">
            <thead>
                <tr>
                    <th>Bulan</th>
                    <th>Persentase</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Januari</td>
                    <td>100%</td>
                </tr>
                <tr>
                    <td>Februari</td>
                    <td>20%</td>
                </tr>
                <tr>
                    <td>Maret</td>
                    <td>30%</td>
                </tr>
                <tr>
                    <td>April</td>
                    <td>40%</td>
                </tr>
                <tr>
                    <td>Mei</td>
                    <td>50%</td>
                </tr>
                <tr>
                    <td>Juni</td>
                    <td>60%</td>
                </tr>
                <tr>
                    <td>Juli</td>
                    <td>60%</td>
                </tr>
                <tr>
                    <td>Agustus</td>
                    <td>60%</td>
                </tr>
                <tr>
                    <td>September</td>
                    <td>60%</td>
                </tr>
                <tr>
                    <td>Oktober</td>
                    <td>60%</td>
                </tr>
                <tr>
                    <td>November</td>
                    <td>60%</td>
                </tr>
                <tr>
                    <td>Desember</td>
                    <td>60%</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
